apiVersion: apps/v1
kind: Deployment
metadata:
  name: alappas
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alappas
  template:
    metadata:
      labels:
        app: alappas
    spec:
      containers:
      - name: alappas
        image: alexluthor135/alappas:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: alappas-service
  namespace: dev
spec:
  selector:
    app: alappas
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
