Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.define "dsasS" do |server|
    server.vm.hostname = "dsasS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.synced_folder "./confs", "/vagrant_share"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = "2"
    end
    server.vm.provision "shell", inline: <<-SHELL
      INTERFACE=$(ip -o -4 addr show | awk '{print $2, $4}' | grep -v 'lo' | awk '{print $1}' | head -n 1)
      curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="--flannel-iface ${INTERFACE} --node-external-ip 192.168.56.110 --bind-address 192.168.56.110" sh -
      sleep 20
      sudo kubectl apply -n kube-system -f /vagrant_share/app1.yaml --validate=false
      sudo kubectl apply -n kube-system -f /vagrant_share/app2.yaml --validate=false
      sudo kubectl apply -n kube-system -f /vagrant_share/app3.yaml --validate=false
      sudo kubectl apply -n kube-system -f /vagrant_share/ingress.yaml --validate=false
    SHELL
  end
end